### ISSUE TITLE
[🚀] GSoC 2021 Coding Challenges Project Milestones

### ISSUE THREAD

**Issue by the-pro** [juice-shop/juice-shop#1630]
# :rocket: GSoC 2021 Coding Challenges

### Description

This year the GSoC project for coding challenges will include:

- [x] Implementing a component to show emphasised lines in the code snippet
- Either by including a customisable enough syntax highlighter or wrapping up the current syntax highlighter with in a component to do that
- [x] Implementing a feature where the user can select multiple code lines where the vulnerability lies. This might have a  cheat detection mechanism to ensure the user does not cheat
- This is the feature to be implemented with the completion of the first milestone
- A new API will be implemented to retrieve and update the solved and unsolved challenges
- [x] Design a new way to congratulate the user of a solved challenge through shooting confetti on the screen
- [x] Implementing a feature to select the correct fix of the vulnerability from a list of choices. This might include a feature to keep track of the number of attempts taken to find the correct fix
- This will require storing the possible fixes for each snippet
- A CI/CD check might be implemented to detect any refactoring done on the snippet so that the fixes do not deviate much from the snippets
- This will be tracked with the above mention challenge

**Comment by bkimminich** [comment]
## Glitches to fix before releasing v12.9.0

- [ ] The "open multiple stacked snippets" issue we notice during last demo
- [ ] The disabling of the submit buttons only works after you once closed and reopened the coding challenge. If you solve "Find it" and immediately switch back to that tab, you'll again have an enabled submit. Same after solving "Fix it".
- [ ] After solving "Fix it" the code snippet displayed should be the correct one and the select dropdown should be disabled (currently it'll show a random one, so that could confuse people thinking that this is the correct when it isn't in 3/4 of times)
- [ ] After solving "Find it" when reopening the coding challenge the correct lines should be marked right away (and deselecting or selecting other lines shouidn't be possible)

**Comment by bkimminich** [comment]
- [ ] Persistence of "Find it"-progress to a `continueCodeFindIt`
- [ ] Persistence of "Fix it"-progress to a `continueCodeFixIt`
- [ ] Include both new cookies in local backup mechanism (no version change, compatible extension of JSON model)
