### ISSUE TITLE
Remove all Dockerfile aliases

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#361]
It is not really necessary to build anything but one version of the Docker image. Having multiple images with different node.js versions was a useless added complexity.

### Tasks
* [x] Remove all version specific `.df` files
* [x] Delete all build jobs on DockerHub except `snapshot` and `latest`
* [ ] Delete existing tags on DockerHub _(post-release optional task for cleanup)_

This is an incompatible change and would have to trigger the v5.0.0 release!
