### ISSUE TITLE
Angular UI - Glitch and TODO collection

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#634]
## Critical Priority
* [x] Responsiveness broken (e.g. Search results page)
  * https://stackoverflow.com/questions/45290746/is-angular-4-material-responsive-like-bootstrap
  * Maybe use https://github.com/angular/flex-layout?
* [x] Simplify the way theming works and make it more Angular-style instead of trying to keep the old Bootswatch themes alive
  * https://medium.com/@tomastrajan/the-complete-guide-to-angular-material-themes-4d165a9d24d1
  * see also https://owasp.slack.com/archives/GAVTB1UCQ/p1533060566000308
* [x] Restoring the hacking progress via `continueCode` cookie does not work. Score Board is cleared on server restart.

## High Priority
* [x] Inconsistent font
* [x] Inconsistent text color
* [x] Product images are distorted (i.e. do not honor aspect ration when resizing)
* [ ] Add likesCount for product reviews on templates
* [x] Browser title is "Frontend"
* [x] App name and version in navbar are underlined
* [x] Page title is static _OWASP Juice Shop_

## Normal Priority
* [x] Toggle buttons have no visually distinguishable state (Score Board, Basket)
* [x] Score Board toggle buttons do not trigger when embedded SVG "⭐️" is clicked
* [x] Feedback carousel not implemented (e.g. use https://www.npmjs.com/package/ng-simple-slideshow) on _About Us_
* [x] Social media button bar missing on _About Us_
* [x] Search result page has scrollbars
* [x] Cookie banner is missing
* [x] `favicon()` route has (accidentally?) been removed from backend
* [x] Language selection is truncated even for short texts, e.g. `English` becomes `E...`
* [x] Language selection is not persisted via cookie

**Comment by J12934** [comment]
- [x] XSS challenge descriptions are malformed on the scoreboard
- [x] XSS1 detection appears to be still not to be working. (Tried `<iframe src="javascript:alert('xss')">` and doesn't solve the challenge but opens the alert)

**Comment by Aashish683** [comment]
@J12934 , I checked up with XSS1 detection and it works with `<iframe src="javascript:alert('xss')"></iframe>`.

**Comment by bkimminich** [comment]
XSS challenge descriptions look okay as well:
![image](https://user-images.githubusercontent.com/3531020/43790885-354244f0-9a74-11e8-9efd-4d5e87ef87bf.png)

**Comment by bkimminich** [comment]
Just noticed the cookie banner is also missing. Add it to the list.

**Comment by bkimminich** [comment]
Here are some screenshots from my mobile phone which illustrate the broken responsiveness currently experienced in the new frontend.

# Angular + Material (8.0.0-SNAPSHOT)
![screenshot_20180825-072913](https://user-images.githubusercontent.com/3531020/44622438-a6c24b00-a8b8-11e8-89e8-518bf9cae116.png) ![screenshot_20180825-072731](https://user-images.githubusercontent.com/3531020/44622439-a6c24b00-a8b8-11e8-9379-705e1a7a8fe8.png) ![screenshot_20180825-072817](https://user-images.githubusercontent.com/3531020/44622440-a6c24b00-a8b8-11e8-825a-148da44c895d.png) ![screenshot_20180825-072857](https://user-images.githubusercontent.com/3531020/44622441-a75ae180-a8b8-11e8-9d88-f6a8063b555b.png)

For comparison, see below.

# AngularJS + Bootstrap (7.x)
![screenshot_20180825-072923](https://user-images.githubusercontent.com/3531020/44622444-b9d51b00-a8b8-11e8-97f0-aaef58660e09.png) ![screenshot_20180825-072801](https://user-images.githubusercontent.com/3531020/44622445-ba6db180-a8b8-11e8-92c0-ec5a57b4ab38.png) ![screenshot_20180825-072847](https://user-images.githubusercontent.com/3531020/44622446-ba6db180-a8b8-11e8-9c4f-d346ef5a3bf3.png)

**Comment by bkimminich** [comment]
Update: Except for the Recycle and Search Result pages everything now properly scales to different screen sizes. Also, I used one pre-built theme now consequently without overriding too many colors.

**Comment by bkimminich** [comment]
Search results are now responsive (hide description column on smaller screens). TODO: Modal dialogs also turned out to miss responsive layout ~, navbar with Score Board button still overflows~.

**Comment by bkimminich** [comment]
I repaired/rewrote the theming mechanism to work similar to the Bootswatch way by naming actual themes in the config, not colors. Color picking would get too messy with dynamic SCSS compiling etc. By providing canned themes those can all be precompiled and then simply switched by `<body class="...">` replacement during startup. Customization of the Easter Egg Tier 2 goodie now also works again.

Proper link colorization is now also repaired based on the above theming mechanism.

(For the record: Bootstrap/Bootswatch was sooooooooooo much simpler... :grimacing:)

**Comment by bkimminich** [comment]
Opened separate ticket for likes counter, everything else is addressed or fixed.
